Repository ISIS3510-202510-G21/Dart-G21, pull requests merged in 2025-05, with the labels that each got.

#65 micro optimizations on eventslist
  lib/widgets/eventslist.dart
Labels: microoptimization

#66 60 sprint 4 implement micro optimizations in searcheventsview
  lib/views/searchevent_view.dart
Labels: microoptimization

#67 ProfileView Micro-optimizations
  lib/views/profile_view.dart
  lib/widgets/about_section.dart
  lib/widgets/follower_stats.dart
  lib/widgets/profile_header.dart
Labels: microoptimization

#68 MyEventsView micro-optimizations
  lib/views/myevents_view.dart
  lib/widgets/eventcardMyEvents_view.dart
Labels: microoptimization

#70 Develop
  README.md
  lib/views/signup_view.dart
Labels: documentation

#72 61 sprint 4 implement followers and following view
  lib/controllers/profile_controller.dart
  lib/controllers/user_controller.dart
  lib/data/dao/profile_dao.dart
  lib/data/dao/user_dao.dart
  lib/data/database/app_database.dart
  lib/data/database/app_database.g.dart
  lib/models/tables.dart
  lib/repositories/drift_repository.dart
  lib/repositories/localStorage_repository.dart
  lib/repositories/profile_repository.dart
  lib/views/FollowersOrFollowingView.dart
  lib/views/categoriesfilter_view.dart
  lib/views/profile_view.dart
  lib/widgets/follower_stats.dart
  lib/widgets/profileCard.dart
Labels: enhancement

#73 71 sprint 4 implement selected categories screen logic
  lib/main.dart
  lib/models/signup_draft.dart
  lib/services/local_storage_service.dart
  lib/views/selectcategories_view.dart
  lib/views/signin_view.dart
  lib/views/splash_view.dart
Labels: enhancement
